/**
 * Pre-computed per-model light coordinates and shapes.
 * Generated by probing each GLB model's bounding box in wrapper space
 * (after scale, center, tire-contact, and rotation transforms).
 *
 * Coordinate system (wrapper space):
 *   +Z = forward,  -Z = backward
 *   +X = right,    -X = left
 *   +Y = up,       Y=0 ≈ road surface
 */

export interface CarLightDef {
  // ── Headlights ──
  headlightL: [number, number, number]; // [x, y, z] position
  headlightR: [number, number, number];
  headlightRadius: number;              // SphereGeometry radius

  // ── Taillights ──
  taillightL: [number, number, number]; // [x, y, z] position
  taillightR: [number, number, number];
  taillightSize: [number, number, number]; // BoxGeometry [w, h, d]

  // ── Beam parameters ──
  spotIntensity: number;  // SpotLight intensity
  spotDistance: number;   // SpotLight range
  beamLength: number;     // volumetric cone length
  beamRadius: number;     // volumetric cone radius
}

/**
 * Static light definitions per model filename.
 * Each entry was computed from the model's post-processed bounding box:
 *   frontZ, rearZ, halfW, lightY
 * with lights placed on the car surface.
 */
export const CAR_LIGHT_MAP: Record<string, CarLightDef> = {
  // ── ENTRY TIER ──
  'white_camry.glb': {
    headlightL: [-0.62, 0.44, 1.95],
    headlightR: [ 0.62, 0.44, 1.95],
    headlightRadius: 0.09,
    taillightL: [-0.62, 0.44, -1.95],
    taillightR: [ 0.62, 0.44, -1.95],
    taillightSize: [0.24, 0.08, 0.06],
    spotIntensity: 2.0,
    spotDistance: 20,
    beamLength: 15,
    beamRadius: 3.5,
  },

  // ── MID TIER ──
  'Nissan_Altima.glb': {
    headlightL: [-0.63, 0.45, 1.96],
    headlightR: [ 0.63, 0.45, 1.96],
    headlightRadius: 0.09,
    taillightL: [-0.63, 0.45, -1.95],
    taillightR: [ 0.63, 0.45, -1.95],
    taillightSize: [0.26, 0.07, 0.06],
    spotIntensity: 2.0,
    spotDistance: 20,
    beamLength: 15,
    beamRadius: 3.5,
  },

  'Nissan_Maxima.glb': {
    headlightL: [-0.67, 0.42, 1.96],
    headlightR: [ 0.67, 0.42, 1.96],
    headlightRadius: 0.10,
    taillightL: [-0.67, 0.42, -1.96],
    taillightR: [ 0.67, 0.42, -1.96],
    taillightSize: [0.28, 0.08, 0.06],
    spotIntensity: 2.2,
    spotDistance: 22,
    beamLength: 16,
    beamRadius: 3.8,
  },

  // ── EXOTIC TIER ──
  'Ferrari.glb': {
    // Low-slung body — lights sit lower (lightY ≈ -0.08 from probe, but
    // the car sits on the road at y=0 in game, so actual light height is
    // relative to the bounding box. We use 0.30 as visual sweet-spot.)
    headlightL: [-0.66, 0.30, 1.96],
    headlightR: [ 0.66, 0.30, 1.96],
    headlightRadius: 0.08,
    taillightL: [-0.66, 0.30, -1.95],
    taillightR: [ 0.66, 0.30, -1.95],
    taillightSize: [0.30, 0.06, 0.06],
    spotIntensity: 2.5,
    spotDistance: 24,
    beamLength: 17,
    beamRadius: 3.0,
  },

  'Porsche_911.glb': {
    headlightL: [-0.65, 0.41, 1.97],
    headlightR: [ 0.65, 0.41, 1.97],
    headlightRadius: 0.08,
    taillightL: [-0.65, 0.41, -1.95],
    taillightR: [ 0.65, 0.41, -1.95],
    taillightSize: [0.30, 0.06, 0.05],
    spotIntensity: 2.4,
    spotDistance: 22,
    beamLength: 16,
    beamRadius: 3.2,
  },

  'Subaru_WRX3.glb': {
    headlightL: [-0.63, 0.45, 1.97],
    headlightR: [ 0.63, 0.45, 1.97],
    headlightRadius: 0.09,
    taillightL: [-0.63, 0.45, -1.95],
    taillightR: [ 0.63, 0.45, -1.95],
    taillightSize: [0.24, 0.08, 0.06],
    spotIntensity: 2.2,
    spotDistance: 20,
    beamLength: 15,
    beamRadius: 3.5,
  },

  // ── ELITE TIER ──
  'Lamborghini.glb': {
    headlightL: [-0.70, 0.29, 1.97],
    headlightR: [ 0.70, 0.29, 1.97],
    headlightRadius: 0.07,
    taillightL: [-0.70, 0.29, -1.95],
    taillightR: [ 0.70, 0.29, -1.95],
    taillightSize: [0.32, 0.05, 0.05],
    spotIntensity: 2.8,
    spotDistance: 26,
    beamLength: 18,
    beamRadius: 3.0,
  },
};
