/**
 * Pre-computed per-model light coordinates and shapes.
 * Generated by probing each GLB model's bounding box in wrapper space
 * (after scale, center, tire-contact, and rotation transforms).
 *
 * Coordinate system (wrapper space):
 *   +Z = forward,  -Z = backward
 *   +X = right,    -X = left
 *   +Y = up,       Y=0 ≈ road surface
 */

export interface CarLightDef {
  // ── Headlights (flat decals on front face) ──
  headlightL: [number, number, number]; // [x, y, z] position
  headlightR: [number, number, number];
  headlightSize: [number, number];      // [width, height] of decal plane

  // ── Taillights (flat decals on rear face) ──
  taillightL: [number, number, number]; // [x, y, z] position
  taillightR: [number, number, number];
  taillightSize: [number, number];      // [width, height] of decal plane

  // ── Beam parameters ──
  spotIntensity: number;  // SpotLight intensity
  spotDistance: number;   // SpotLight range
  beamLength: number;     // volumetric cone length
  beamRadius: number;     // volumetric cone radius
}

/**
 * Static light definitions per model filename.
 * Headlights: warm-white flat decals flush against the front bumper.
 * Taillights: red flat decals flush against the rear bumper.
 */
export const CAR_LIGHT_MAP: Record<string, CarLightDef> = {
  // ── ENTRY TIER ──
  'white_camry.glb': {
    headlightL: [-0.627, 0.658, 1.583],
    headlightR: [ 0.627, 0.658, 1.583],
    headlightSize: [0.2, 0.1],
    taillightL: [ 0.527, 0.738, -1.833],
    taillightR: [-0.527, 0.738, -1.833],
    taillightSize: [0.2, 0.1],
    spotIntensity: 2.0,
    spotDistance: 20,
    beamLength: 15,
    beamRadius: 3.5,
  },

  // ── MID TIER ──
  'Nissan_Altima.glb': {
    headlightL: [-0.63, 0.45, 1.96],
    headlightR: [ 0.63, 0.45, 1.96],
    headlightSize: [0.24, 0.13],
    taillightL: [-0.63, 0.45, -1.95],
    taillightR: [ 0.63, 0.45, -1.95],
    taillightSize: [0.30, 0.09],
    spotIntensity: 2.0,
    spotDistance: 20,
    beamLength: 15,
    beamRadius: 3.5,
  },

  'Nissan_Maxima.glb': {
    headlightL: [-0.67, 0.42, 1.96],
    headlightR: [ 0.67, 0.42, 1.96],
    headlightSize: [0.26, 0.14],
    taillightL: [-0.67, 0.42, -1.96],
    taillightR: [ 0.67, 0.42, -1.96],
    taillightSize: [0.32, 0.10],
    spotIntensity: 2.2,
    spotDistance: 22,
    beamLength: 16,
    beamRadius: 3.8,
  },

  'Ford_Mustang.glb': {
    headlightL: [-0.65, 0.40, 1.96],
    headlightR: [ 0.65, 0.40, 1.96],
    headlightSize: [0.24, 0.12],
    taillightL: [-0.65, 0.40, -1.95],
    taillightR: [ 0.65, 0.40, -1.95],
    taillightSize: [0.30, 0.08],
    spotIntensity: 2.2,
    spotDistance: 22,
    beamLength: 16,
    beamRadius: 3.5,
  },

  // ── EXOTIC TIER ──
  'Ferrari.glb': {
    headlightL: [-0.66, 0.30, 1.96],
    headlightR: [ 0.66, 0.30, 1.96],
    headlightSize: [0.20, 0.08],
    taillightL: [-0.66, 0.30, -1.95],
    taillightR: [ 0.66, 0.30, -1.95],
    taillightSize: [0.34, 0.06],
    spotIntensity: 2.5,
    spotDistance: 24,
    beamLength: 17,
    beamRadius: 3.0,
  },

  'Porsche_911.glb': {
    headlightL: [-0.65, 0.41, 1.97],
    headlightR: [ 0.65, 0.41, 1.97],
    headlightSize: [0.18, 0.10],
    taillightL: [-0.65, 0.41, -1.95],
    taillightR: [ 0.65, 0.41, -1.95],
    taillightSize: [0.36, 0.06],
    spotIntensity: 2.4,
    spotDistance: 22,
    beamLength: 16,
    beamRadius: 3.2,
  },

  'Subaru_WRX3.glb': {
    headlightL: [-0.63, 0.45, 1.97],
    headlightR: [ 0.63, 0.45, 1.97],
    headlightSize: [0.22, 0.14],
    taillightL: [-0.63, 0.45, -1.95],
    taillightR: [ 0.63, 0.45, -1.95],
    taillightSize: [0.26, 0.10],
    spotIntensity: 2.2,
    spotDistance: 20,
    beamLength: 15,
    beamRadius: 3.5,
  },

  // ── ELITE TIER ──
  'Lamborghini.glb': {
    headlightL: [-0.70, 0.29, 1.97],
    headlightR: [ 0.70, 0.29, 1.97],
    headlightSize: [0.16, 0.06],
    taillightL: [-0.70, 0.29, -1.95],
    taillightR: [ 0.70, 0.29, -1.95],
    taillightSize: [0.38, 0.04],
    spotIntensity: 2.8,
    spotDistance: 26,
    beamLength: 18,
    beamRadius: 3.0,
  },
};

// ── Persistence Layer ── //
const CALIBRATION_STORAGE_KEY = 'irl-race-calibration-overrides';

export function saveCalibrationOverride(modelId: string, def: CarLightDef) {
  CAR_LIGHT_MAP[modelId] = def;
  try {
    const existingStr = localStorage.getItem(CALIBRATION_STORAGE_KEY);
    const overrides = existingStr ? JSON.parse(existingStr) : {};
    overrides[modelId] = def;
    localStorage.setItem(CALIBRATION_STORAGE_KEY, JSON.stringify(overrides));
  } catch (e) {
    console.warn('Failed to save calibration override', e);
  }
}

export function loadCalibrationOverrides() {
  try {
    const existingStr = localStorage.getItem(CALIBRATION_STORAGE_KEY);
    if (!existingStr) return;
    const overrides = JSON.parse(existingStr);
    if (typeof overrides !== 'object' || overrides === null) return; // audit fix #16
    for (const modelId in overrides) {
      const def = overrides[modelId];
      // Audit fix #16: basic type validation to prevent corrupted data from crashing
      if (!def || typeof def !== 'object') continue;
      if (!Array.isArray(def.headlightL) || def.headlightL.length !== 3) continue;
      if (typeof def.spotIntensity !== 'number') continue;
      if (CAR_LIGHT_MAP[modelId]) {
        Object.assign(CAR_LIGHT_MAP[modelId], def);
      } else {
        CAR_LIGHT_MAP[modelId] = def;
      }
    }
  } catch (e) {
    console.warn('Failed to load calibration overrides', e);
  }
}

// Load overrides immediately upon module evaluation
loadCalibrationOverrides();
